version: '3'
services:
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: